### ISSUE TITLE
Feature: Enable lightweight solution

### ISSUE THREAD

**Issue by sclarke81** [cyotek/Cyotek.AddProjects#10]
The extension could offer the option to enable lightweight solution if supported (it's a VS2017 feature). This could be as an option on the dialog and/or as a prompt if the user selects a lot of projects. A brief description of lightweight solution load would probably be useful too.

_Sent from my Motorola Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cyotek** [comment]
Interesting; I didn't even know this was a thing. Wonder if it actually works - I find the background project load introduced in earlier versions to be worse than just loading the whole solution right away, so much so that I usually press F6 while the "background" load is ongoing to force the whole thing to actually foreground load so I get on with things. Of course Resharper is the biggest destroy of performance in the known universe and so doesn't help with open times. I'm not sure that the AddProjects extension could work with this setting, but it is definitely worth investigating.

**Comment by wooftydoo** [comment]
Lightweight solutions were deprecated in 15.5. https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.5

**Comment by cyotek** [comment]
Closing this as they have been deprecated for a while and it's not likely I was going to get time to add it anyway.
