### ISSUE TITLE
Not working with VS2019

### ISSUE THREAD

**Issue by GioAbq** [cyotek/Cyotek.AddProjects#18]
VSIX installation stops on error:
![2019-04-03 10_34_30-VSIX Installer](https://user-images.githubusercontent.com/7473827/55464774-2016de80-55fc-11e9-9e28-fe7414fb4206.png)

**Comment by cyotek** [comment]
Hello,

Thanks for the notification. I plan on installing VS2019 RTM on a fresh Windows install this weekend, I'll take a look at making it compatible then. 

Thanks again for the issue report!

Regards;
Richard Moss

**Comment by AmitGee** [comment]
Below is the excerpt from the log file. I tried installing the 4.6.* targeting packs and SDKs, didn't help:

01/07/2019 17:52:43 - Extension cannot be installed to the following products due to missing prerequisites:
01/07/2019 17:52:43 - 	Microsoft Visual Studio Professional 2019
01/07/2019 17:52:43 - 		-------------------------------------------------------
01/07/2019 17:52:43 - 		Identifier   : Microsoft.Net.ComponentGroup.TargetingPacks.Common
01/07/2019 17:52:43 - 		Name         : .NET Framework 4 ... 4.6 development tools
01/07/2019 17:52:43 - 		Version      : [15.0.26606.0,16.0)
01/07/2019 17:52:43 - 		Error        : The prerequisite version specified does not match the version installed
01/07/2019 17:52:43 -

**Comment by benmccallum** [comment]
Just installed version onto VS 2019 Community 16.3 and it seemed to work. Phewf. Moving hundreds of projects into a mono repo and this is a life saver! Thanks ❤️

**Comment by cyotek** [comment]
Hello,

Firstly, I apologise for just how long it has taken me to get around to this. I upgraded the project this morning to work with Visual Studio 2019 and the new async extension model. I haven't extensively tested it but it seems to be working - there's a caveat that file filters are being duplicated but this doesn't seem to be a new bug judging from the state of my own configuration file, I'll look into that in due course.

As usual I haven't tried to make one extension work with multiple versions of Visual Studio so this is a brand new extension. It's also not published on the Marketplace yet, I haven't tested it enough, I've forgotten how to code sign packages, and so I need time for that. You can download the VS2019 release from the Releases page in this repository though - I hope it is still useful.

I'm going to leave this issue open until I've published it to the marketplace, but please free free to open new issues if you identify any problems with this new build.
