### ISSUE TITLE
Search should delegate to file system instead of enumerating every single file

### ISSUE THREAD

**Issue by gkinsman** [cyotek/Cyotek.AddProjects#2]
L106 of FindProjectsDialog:

``` csharp
foreach (string fileName in Directory.GetFiles(path, "*.*", SearchOption.AllDirectories))
{
    if (_searchPattern.IsMatch(fileName) &&
        !_existingFiles.Any(f => string.Equals(f, fileName, StringComparison.InvariantCultureIgnoreCase)))
    {
        projectsListView.AddFile(fileName, true);
    }
}
```

This should delegate to the file system instead of enumerating every file, which is incredibly expensive and makes this extension unusable on any project with a node_modules. 

Instead, consider making the search pattern compatible with the Directory.GetFiles API and handle the returned files. I'll PR this if I get time tonight :).

**Comment by cyotek** [comment]
Hello,

Thanks for the bug report! I actually only have a couple of solutions making use of node, and as they are self-contained I've never used Add Projects with them to spot this issue. In my normal code, I use `FindFirstFile` / `FindNextFile` in an iterator to avoid the string array, and also prefixed with `\\?\` to allow extended path support. As Add Projects was a quick and dirty project (and my first attempt at a VS extension), the code probably contains a multitude of sins. It would probably be better if it could also skip folders such as bin, obj and the mentioned node_modules.

If you find the time to submit a PR, be my guest, otherwise I'll try and get to it shortly(ish).

Thanks again for the report.

Regards;
Richard Moss

**Comment by gkinsman** [comment]
Sorry for being a little bit brief and blunt before - it's a cool idea for an extension!

To clarify a little further, I think this code could be more efficient if instead it did this:

``` csharp
foreach (string fileName in Directory.EnumerateFiles("C:\", "*.*proj", SearchOption.AllDirectories))
{
    // Handle project file
}
```

EnumerateFiles will return immediately and lazily enumerate the files, whereas GetFiles will block until all of the files have been returned. Using EnumerateFiles will give you an IEnumerable, so you can also filter the results further with a `.Where`. Using a path filter like `*.*proj` will also give the file system more information to exclude irrelevant files, further speeding it up.

It's possible this could still be quite slow in the presence of node_modules due to the number of files it has to handle, though you could add specific filters for those directories, perhaps necessitating a manual recursive search to exclude them.

Sorry I didn't get around to it last night - will try soon!

Cheers
George

**Comment by cyotek** [comment]
George,

Thanks for the follow up. I have to admit, I invariably forget about `EnumerateFiles` as it was added in 4.0 and it was only recently (i.e. when MS killed off support) that I finally moved everything internal from 3.5 to 4.6.

No worries if you don't have time to do a PR (we're all busy :)), I'll take a look at the weekend to add some directory filters and use `EnumerateFiles`.

Regards;
Richard Moss

**Comment by cyotek** [comment]
Hello,

Just to let you know, no need to raise a PR - I've updated my local copy with a fix and will be updating this source and the published extension shortly once I've finished my tinkering.

Regards;
Richard Moss

**Comment by cyotek** [comment]
New build posted which should resolve this. I also added some extremely basic exclusion filtering so that `node_modules`, `bower_components` et al can be excluded. Hopefully these changes meet your needs, if not feel free to open a new issue.
